import 'dart:io';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import '../../core/utils/logger.dart';
import 'package:mapbox_maps_flutter/mapbox_maps_flutter.dart' hide ImageSource;
import 'package:geolocator/geolocator.dart' as geo;
import 'package:provider/provider.dart';
import '../../core/theme/app_colors.dart';
import '../../domain/entities/report.dart';
import '../../domain/repositories/report_repository.dart';
import '../providers/auth_provider.dart';
import '../../data/datasources/report_data_source.dart';
import '../../data/repositories/report_repository_impl.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

class ReportScreen extends StatefulWidget {
  const ReportScreen({super.key});

  @override
  State<ReportScreen> createState() => _ReportScreenState();
}

class _ReportScreenState extends State<ReportScreen> {
  File? _imageFile;
  PollutionType _pollutionType = PollutionType.plastic;
  int _severity = 3;
  final _notesController = TextEditingController();
  bool _isGlobalSubmitting = false;
  Point? _currentLocation;

  // Dependency Injection (simplified for now)
  late final ReportRepository _reportRepository;

  @override
  void initState() {
    super.initState();
    _reportRepository =
        ReportRepositoryImpl(ReportDataSource(Supabase.instance.client));
    _detectLocation();
  }

  Future<void> _detectLocation() async {
    try {
      final position = await geo.Geolocator.getCurrentPosition();
      setState(() {
        _currentLocation =
            Point(coordinates: Position(position.longitude, position.latitude));
      });
    } catch (e) {
      AppLogger.error('Error getting location: $e');
    }
  }

  Future<void> _pickImage(ImageSource source) async {
    final picker = ImagePicker();
    final pickedFile = await picker.pickImage(source: source);
    if (pickedFile != null) {
      setState(() => _imageFile = File(pickedFile.path));
    }
  }

  Future<void> _submitReport() async {
    if (_imageFile == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
            content: Text('Please attach a photo of the pollution.')),
      );
      return;
    }
    if (_currentLocation == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Detecting location... please wait.')),
      );
      await _detectLocation();
      if (!mounted) return;
      if (_currentLocation == null) return;
    }

    setState(() => _isGlobalSubmitting = true);

    try {
      final user = context.read<AuthProvider>().currentUser;
      if (user == null) throw Exception('User not logged in');

      final report = ReportEntity(
        id: '', // Generated by DB or Repo
        userId: user.id,
        location: _currentLocation!,
        pollutionType: _pollutionType,
        severity: _severity,
        notes: _notesController.text,
        reportedAt: DateTime.now(),
      );

      await _reportRepository.createReport(
          report: report, imageFile: _imageFile!);

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: const Text('Report submitted successfully!'),
            backgroundColor: Theme.of(context).colorScheme.primary,
          ),
        );
        Navigator.pop(context);
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Failed to submit report: $e'),
            backgroundColor: AppColors.punchRed,
          ),
        );
      }
    } finally {
      if (mounted) setState(() => _isGlobalSubmitting = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    final primaryColor = Theme.of(context).colorScheme.primary;

    return Scaffold(
      appBar: AppBar(
        title: const Text('New Report'),
        backgroundColor: Colors.transparent,
        elevation: 0,
      ),
      extendBodyBehindAppBar: true,
      body: _isGlobalSubmitting
          ? const Center(child: CircularProgressIndicator())
          : SingleChildScrollView(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  // Image Section
                  GestureDetector(
                    onTap: () => _pickImage(ImageSource.camera),
                    child: Container(
                      height: 300,
                      decoration: BoxDecoration(
                        color: isDark ? Colors.grey[900] : Colors.grey[200],
                        image: _imageFile != null
                            ? DecorationImage(
                                image: FileImage(_imageFile!),
                                fit: BoxFit.cover,
                              )
                            : null,
                      ),
                      child: _imageFile == null
                          ? Column(
                              mainAxisAlignment: MainAxisAlignment.center,
                              children: [
                                Icon(Icons.camera_alt,
                                    size: 64, color: primaryColor),
                                const SizedBox(height: 16),
                                const Text('Tap to take photo'),
                              ],
                            )
                          : null,
                    ),
                  ),

                  Padding(
                    padding: const EdgeInsets.all(24.0),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        // Pollution Type
                        Text('Pollution Type',
                            style: Theme.of(context).textTheme.titleMedium),
                        const SizedBox(height: 8),
                        Wrap(
                          spacing: 8,
                          children: PollutionType.values.map((type) {
                            final isSelected = _pollutionType == type;
                            return ChoiceChip(
                              label: Text(type.name.toUpperCase()),
                              selected: isSelected,
                              selectedColor: primaryColor,
                              onSelected: (selected) {
                                if (selected) {
                                  setState(() => _pollutionType = type);
                                }
                              },
                            );
                          }).toList(),
                        ),

                        const SizedBox(height: 24),

                        // Severity
                        Text('Severity (1-5)',
                            style: Theme.of(context).textTheme.titleMedium),
                        Slider(
                          value: _severity.toDouble(),
                          min: 1,
                          max: 5,
                          divisions: 4,
                          label: _severity.toString(),
                          activeColor: primaryColor,
                          onChanged: (val) =>
                              setState(() => _severity = val.round()),
                        ),

                        const SizedBox(height: 24),

                        // Notes
                        TextField(
                          controller: _notesController,
                          decoration: InputDecoration(
                            labelText: 'Notes (Optional)',
                            border: OutlineInputBorder(
                                borderRadius: BorderRadius.circular(12)),
                          ),
                          maxLines: 3,
                        ),

                        const SizedBox(height: 32),

                        // Submit Button
                        SizedBox(
                          width: double.infinity,
                          height: 56,
                          child: FilledButton(
                            onPressed: _submitReport,
                            style: FilledButton.styleFrom(
                              backgroundColor: primaryColor,
                              shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(16)),
                            ),
                            child: const Text('Submit Report',
                                style: TextStyle(
                                    fontSize: 18, fontWeight: FontWeight.bold)),
                          ),
                        ),
                        const SizedBox(height: 32),
                      ],
                    ),
                  ),
                ],
              ),
            ),
    );
  }
}
